apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "olm-cleanup"
  namespace: "openshift-managed-node-metadata-operator"
  annotations:
    package-operator.run/phase: cleanup-rbac
    package-operator.run/collision-protection: IfNoController
rules:
  - apiGroups:
      - "operators.coreos.com"
    resources:
      - "clusterserviceversions"
      - "subscriptions"
    verbs:
      - list
      - get
      - watch
      - delete
