apiVersion: v1
kind: ServiceAccount
metadata:
  name: olm-cleanup
  namespace: openshift-managed-node-metadata-operator
  annotations:
    package-operator.run/phase: cleanup-rbac
    package-operator.run/collision-protection: IfNoController
